# 条款08：避免析构函数抛出异常

## 析构函数的调用

```C++
class Widget {
public:
    ...
    ~Widget( ) { ... }
};
void doSomething()
{
    std::vector<Widget> v;
    ...
}							//v在此处被销毁(调用析构函数)
```

+ $C++$ 不喜欢析构函数吐出异常
+ 若 `vector` 内存有10个 `Widget` 对象，一旦在销毁的过程中抛出过多异常，会导致程序结束执行或是不明确行为（本例中会是不明确行为）
+ 使用其他容器，例如 `list`、`set` 或 `TR1` 的任何容器（[条款54]()），也一样会导致异常



## 析构函数的异常

+ 负责数据库连接的 `class` ：

    ```C++
    class DBConnection {				//负责数据库连接
    public:
        ...
        static DBConnection create();	//这个函数返回DBConnection对象
        void close();					//关闭联机，失败则抛出异常
    };
    ```

+ 资源管理 `class` ：

    **为确保在客户忘记调用 `close()` ，在资源管理 `class` 的析构函数中调用 `close()`**

    ```C++
    class DBConn {
    public:
        ...
        ~DBConn()					//确保数据库总是会被关闭
        {
            db.close();				//如果close抛出异常，DBConn析构函数会传播异常
        }
    private:
        DBConnection db;
    };
    ```

+ 若调用 `close` 的过程中抛出异常， `DBConn` 析构函数会传播异常，即允许它离开析构函数，便会造成难以驾驭的麻烦



## 解决抛出异常问题的方法

### 1. 调用`abort`，强迫结束程序

```C++
DBConn::~DBConn( )
{
    try{ db.close(); }
    catch (...) {
        ...						//制作运转记录，记下对close的调用失败
        std::abort( );
    }
}
```

+ 调用 `abort` 强制结束程序，可以抢先阻止不明确行为



### 2. 吞掉异常，仅记下异常信息

```C++
DBConn::~DBConn( )
{
    try{ db.close(); }
    catch (...) {
        ...						//制作运转记录，记下对close的调用失败
    }
}
```

+ 一般来说吞掉异常是个坏主意，但是若程序必须能够继续可靠地执行（即使遇到错误之后），则可以选择这个方案



### 3. 将风险的处理机会交给客户

**`DBConn` 自己提供一个 `close` 函数，供客户调用，若客户忽略调用 `close` 函数，则通过析构函数调用**

```C++
class DBConn {
public:
    ...
    void close()						//供客户使用的新函数
    {
        db.close();
        closed = true;
    }
    ~DBConn()
    {
        if (!closed) {					//如果客户不关闭连接，则自动关闭连接
            try{ db.close(); }
            catch (...) {
                ...						//制作运转记录，记下对close的调用失败
                ...						//吞下或不吞下异常
            }
        }
    }
private:
    DBConnection db;
    bool closed;
};
```

